spring:
  application:
    name: store1

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200
    refreshTokenExpiration: 604800

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}